AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: desafio-2-async
  
Globals:
  Function:
    Timeout: 3

Resources:

  SQSMiddleware:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'SQSQueue'

  PassAsyncFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pass-function/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSMiddleware.Arn
